### ISSUE TITLE
nothing appears in room space when sending general message

### ISSUE THREAD

**Issue by ludetie** [SomajitDey/ipfs-chat#15] opened 2021-09-25 11:42 UTC

**Comment by ludetie** [comment] 2021-09-25 11:45
![gkrellShoot_25-09-2021_134437](https://user-images.githubusercontent.com/91374123/134770317-fc6f616a-7811-48f4-8326-95723e09cb3c.jpg)

**Comment by SomajitDey** [comment] 2021-09-26 05:33
Thanks a lot for reporting (👍 for the screenshots). However, I failed to reproduce the issue however I tried.

Kindly report the following:

1. Your IPFS version number: `ipfs-chat -v` and `ipfs --version`
2. If this issue persists when using a different room and different Nicks for both the peers.
3. If this issue persists with option in the pure LAN mode: `ipfs-chat -l`

**Comment by ludetie** [comment] 2021-09-26 10:03
1. ipfs version 0.9.1
2. 0.2.5 (alpha)
3. GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
4. Ubuntu 20.04

9--> gpg (GnuPG) 2.2.19 , libgcrypt 1.8.5

5 & 6 & 8 --> 
I try another room and different nicknames, and i configure with pure LAN mode, but the issue persists

I notice another things : when I want to send a Personal Message, this one is written on the sender screen and does not go to the addressee
![screen](https://user-images.githubusercontent.com/91374123/134803041-83315113-0d08-43ed-b1a0-2192cef92470.jpg)

Also when I want to send a file it does not go to the default directory

7--> no error on exit

Hope you will fix it

Regards,

**Comment by SomajitDey** [comment] 2021-09-26 11:15
Thank you so much for going through everything as requested - I am pretty sure now that it's somehow related to the GPG section of the code or the environment it assumes. This has to be an edge case as no one else reported such an issue. I run the exact same versions as you, so there's no problem. I will try my best to figure out what exactly is going wrong in your case and fix the issue. I will pester you if I need more info.

Although I am trying hard to make time and address this issue, I am compelled to divide my focus between [IPNS-Link](https://github.com/ipns-link/specs) and my work life for a while. So, I am afraid, resolving this issue might take some time. But I am committed to give you the best IPFS-Chat experience. Plz hang in there. Thanks for your support 💚

**Comment by SomajitDey** [comment] 2021-09-26 13:24
@ludetie , Hi I notice in your last screenshots a mysterious `dim.` where there should be the [day of the week](https://github.com/SomajitDey/ipfs-chat/#snapshot). Is your system clock running ok?

Please post the result of the following command: `date +"%a %H:%M:%S"`

**Comment by ludetie** [comment] 2021-09-26 13:45
You're right, this is the day of the week
ludeti@FiercePC:~$ date +"%a %H:%M:%S"
dim. 15:41:11

**Comment by SomajitDey** [comment] 2021-09-26 15:39
@ludetie Your issue, therefore, most likely has nothing to do with the `ipfs-chat` code. Because of this malbehavior of your system time, probably GPG is failing, since GPG uses the timestamp when generating the key internally.

My guess is that the following won't work:

```bash
echo foo | gpg --batch --passphrase pass --pinentry-mode loopback -c -a -o- - | gpg --batch --passphrase pass --pinentry-mode loopback -d -o- -
```
Lemme know the result and the exit code (`echo $?`)

**Comment by ludetie** [comment] 2021-09-26 15:53
![gkrellShoot_26-09-2021_175120](https://user-images.githubusercontent.com/91374123/134814973-cd9eba76-4fe7-4ae4-91aa-1686a4e22908.jpg)
It seems to work.

**Comment by SomajitDey** [comment] 2021-09-26 16:37
@ludetie Ok, I have been able to reproduce your issue by deliberately messing up a line of code involving `date` in `ipfs-chat`. So, it seems like malbehavior of `date` is affecting directly. Plz, do me another favor. Report result of below code:

```bash
date -d @${EPOCHSECONDS} +"%a %H:%M:%S" || echo "Failed"
```

**Comment by ludetie** [comment] 2021-09-26 16:43
@SomajitDey 
![gkrellShoot_26-09-2021_184152](https://user-images.githubusercontent.com/91374123/134816430-483fb79d-b60c-48a7-b100-9e88fbbaa4e5.jpg)

**Comment by SomajitDey** [comment] 2021-09-26 17:05
@ludetie Ah my friend I have found the error I believe. All your commands are outputting French where the `ipfs-chat` code, rather stupidly, looks for the phrase `Good signature from`, in English. My confusion with `dim.` above is similar - I didnt know it means Sun in French. I will make `ipfs-chat` language independent soon and ask you here to test it before I release. Is that ok?

**Comment by ludetie** [comment] 2021-09-26 17:56
Somajit,

Glad you found ! And happy to test ! Thank you.

Le 26 septembre 2021 19:05:23 GMT+02:00, Somajit ***@***.***> a écrit :
***@***.*** Ah my friend I have found the error I believe. All your commands are outputting French where the `ipfs-chat` code, rather stupidly, looks for the phrase `Good signature from`, in English. My confusion with `dim.` above is similar - I didnt know it means Sun in French. I will make `ipfs-chat` language independent soon and ask you here to test it before I release. Is that ok?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SomajitDey/ipfs-chat/issues/15#issuecomment-927337905

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by SomajitDey** [comment] 2021-09-27 07:40
@ludetie Hi, I apologize for the delay. The fix is [available](https://github.com/SomajitDey/ipfs-chat/tree/issue15) for your testing now.

You may access it as follows:
```bash
# Fresh download
git clone https://github.com/SomajitDey/ipfs-chat -b issue15 --depth=1 ipfs-chat_issue15
# Go to downloaded directory
cd ipfs-chat_issue15
# Check your version
./ipfs-chat -v # Should give you 0.2.6(beta)
# Test it
./ipfs-chat
```

Let me know if it works now. I have changed everything to English for `ipfs-chat` only in order to make it future-proof against similar bugs. Hope you don't mind.

**Comment by ludetie** [comment] 2021-09-27 17:03
@SomajitDey Hello !
It works ! Thank you very much !
![screen](https://user-images.githubusercontent.com/91374123/134953511-f758ed4c-583c-4644-846f-e99867824393.jpg)
!
I apologize for the delay too .
Regards,

**Closed** 2021-09-27 17:58 UTC
Labels: bug
